### ISSUE TITLE
Allow rpc functions to take arguments by reference

### ISSUE THREAD

**Issue by Boscop** [google/tarpc#159] opened 2017-06-26 11:53 UTC
Currently it's not possible to make rpc functions take arguments by reference, to avoid cloning.
It says lifetime required, but if I add a lifetime, it says, no rule expected this token.

**Comment by tikue** [comment] 2017-06-26 15:48
I agree this would be a great feature -- tarpc actually used to take all args by reference! The reason it's currently not possible is because messages are not serialized until they're sent to a tokio framed IO, which requires all messages to have the `'static` lifetime. It might be worth checking in with the tokio team to see if they plan to revisit this restriction at any point.

**Comment by tikue** [comment] 2018-09-15 23:48
Because there's a dedicated I/O task, I don't really see this being possible client-side. Did you want it client side or server side, or both?

**Comment by Boscop** [comment] 2018-09-16 03:40
I think it makes sense to take args by ref to avoid cloning where it's possible..

**Comment by tikue** [comment] 2018-09-16 05:26
The problem is there can be multiple clients running on multiple tasks, and they need to send the requests to the I/O task. Since tasks can be running on other threads, args need to be `Send + 'static`.

One thing you could do would be to ref count the parameters that you need to clone? Then you're dynamically allocating, but if it's a long lived object it could be worth it.

**Comment by tikue** [comment] 2018-10-16 22:53
I'm going to close this, because I don't see a way of making it actionable in the short term.

**Closed by tikue** 2018-10-16 22:53 UTC
Labels: feature
