### ISSUE TITLE
Compilation error - Can't find crate for '_serde'

### ISSUE THREAD

**Issue by schoeppl** [google/tarpc#168] opened 2017-09-24 20:27 UTC
There seems to be a problem with the current nightly and Tarpc 0.9.

rustc: "1.22.0-nightly (26015da01 2017-09-23)"
Tarpc: "0.9.0"
Tarpc-plugins: "0.2.0"

Code from github example (Example: Sync).

> error[E0463]:
> 
>  can't find crate for `_serde`
>   --> src\main.rs:13:1
>    |
> 13 | / service! {
> 14 | |     rpc hello(name: String) -> String;
> 15 | | }
>    | |_^ can't find crate

**Comment by ERnsTL** [comment] 2017-09-24 20:52
I can also confirm that compilation error.

**Comment by tikue** [comment] 2017-09-24 21:54
Strangely, I'm not able to reproduce this. Can you provide the exact code that causes this to occur?

**Comment by tikue** [comment] 2017-09-24 21:59
@schoeppl I cloned your tarpctest repo and now am hitting this problem, which makes me think this is some kind of rustc cross-crate bug. Will file an issue upstream.

**Comment by tikue** [comment] 2017-09-24 22:42
I've filed https://github.com/rust-lang/rust/issues/44817. In the meantime, a workaround appears to be to add to your Cargo.toml `serde = "*"`.

 Sorry for the inconvenience; hopefully this will be solved soon!

**Comment by bkfox** [comment] 2017-10-02 02:06
I take the occasion that this issue is opened to report another compilation error (just to avoid to fill a new one for a so small thing to change). It happened when cargo was building tarp-plugins (0.2.0) from dependencies using nightly:

```
error[E0061]: this function takes 1 parameter but 2 parameters were supplied
  --> /home/xxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-plugins-0.2.0/src/lib.rs:68:52
   |
68 |                     *doc = Symbol::intern(&str_lit(&doc.as_str(), None).replace("{}", &old_ident));
   |                                                    ^^^^^^^^^^^^^^^^^^^ expected 1 parameter

error: aborting due to previous error
error: Could not compile `tarpc-plugins`.
```

This can be fixed by removing the second argument of str_lit, such as: `str_lit(&doc.as_str())`.

**Comment by tikue** [comment] 2017-10-02 20:33
@bkfox that change was made to track changes in recent nightlies. You'll probably need to upgrade your version. There was a minor version bump, so `cargo update` shouldn't have updated you to that version, unless you opted in?

**Comment by bl4ck5un** [comment] 2017-10-12 14:18
I can also confirm this bug. Looking forward to a fix.

**Comment by tikue** [comment] 2017-10-12 16:34
Unfortunately I don't know of anyone actively working on pushing macros 2.0 over the finish line. In the meantime, I'll update the readme to mention this problem and its workaround.

**Comment by tikue** [comment] 2024-02-04 08:19
Is anyone still running into this?

**Comment by tikue** [comment] 2024-02-05 02:37
I suspect the fact that tarpc is now reexporting the serde crate solved this. Please reopen if I'm mistaken. Thanks!

**Closed by tikue** 2024-02-05 02:37 UTC
Labels: bug
